// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bonjour.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceAnnouncement struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceAnnouncement) Reset()         { *m = ServiceAnnouncement{} }
func (m *ServiceAnnouncement) String() string { return proto.CompactTextString(m) }
func (*ServiceAnnouncement) ProtoMessage()    {}
func (*ServiceAnnouncement) Descriptor() ([]byte, []int) {
	return fileDescriptor_bonjour_00d00f83c6cefa17, []int{0}
}
func (m *ServiceAnnouncement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAnnouncement.Unmarshal(m, b)
}
func (m *ServiceAnnouncement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAnnouncement.Marshal(b, m, deterministic)
}
func (dst *ServiceAnnouncement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAnnouncement.Merge(dst, src)
}
func (m *ServiceAnnouncement) XXX_Size() int {
	return xxx_messageInfo_ServiceAnnouncement.Size(m)
}
func (m *ServiceAnnouncement) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAnnouncement.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAnnouncement proto.InternalMessageInfo

func (m *ServiceAnnouncement) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ServiceAnnouncement) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceAnnouncement) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceAnnouncement)(nil), "proto.ServiceAnnouncement")
}

func init() { proto.RegisterFile("bonjour.proto", fileDescriptor_bonjour_00d00f83c6cefa17) }

var fileDescriptor_bonjour_00d00f83c6cefa17 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xca, 0xcf, 0xcb,
	0xca, 0x2f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x81, 0x5c,
	0xc2, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x8e, 0x79, 0x79, 0xf9, 0xa5, 0x79, 0xc9, 0xa9,
	0xb9, 0xa9, 0x79, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0xa5, 0xa5, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0xac, 0x20, 0xbf, 0xa8, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x35, 0x08, 0xcc, 0x06, 0x89, 0x95, 0x24, 0xa6, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x83, 0xd4, 0x81,
	0xd8, 0x49, 0x6c, 0x60, 0x93, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0xb8, 0x64, 0x45,
	0x71, 0x00, 0x00, 0x00,
}
