// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code                 uint64   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_83c02257ddd685fb, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ErrorResponse struct {
	Error                *Error   `protobuf:"bytes,536870911,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_83c02257ddd685fb, []int{1}
}
func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (dst *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(dst, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SelfDescribingMessage struct {
	TypeName             string   `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	MessageData          []byte   `protobuf:"bytes,2,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	Error                *Error   `protobuf:"bytes,536870911,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfDescribingMessage) Reset()         { *m = SelfDescribingMessage{} }
func (m *SelfDescribingMessage) String() string { return proto.CompactTextString(m) }
func (*SelfDescribingMessage) ProtoMessage()    {}
func (*SelfDescribingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_83c02257ddd685fb, []int{2}
}
func (m *SelfDescribingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfDescribingMessage.Unmarshal(m, b)
}
func (m *SelfDescribingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfDescribingMessage.Marshal(b, m, deterministic)
}
func (dst *SelfDescribingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfDescribingMessage.Merge(dst, src)
}
func (m *SelfDescribingMessage) XXX_Size() int {
	return xxx_messageInfo_SelfDescribingMessage.Size(m)
}
func (m *SelfDescribingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfDescribingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SelfDescribingMessage proto.InternalMessageInfo

func (m *SelfDescribingMessage) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *SelfDescribingMessage) GetMessageData() []byte {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SelfDescribingMessage) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*ErrorResponse)(nil), "proto.ErrorResponse")
	proto.RegisterType((*SelfDescribingMessage)(nil), "proto.SelfDescribingMessage")
}

func init() { proto.RegisterFile("util.proto", fileDescriptor_util_83c02257ddd685fb) }

var fileDescriptor_util_83c02257ddd685fb = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xc9, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xa6, 0x5c, 0xac, 0xae, 0x45,
	0x45, 0xf9, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x2c, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x64, 0xce, 0xc5, 0x0b, 0xd6, 0x16, 0x94, 0x5a,
	0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xa4, 0xc6, 0xc5, 0x9a, 0x0a, 0x12, 0x90, 0xf8, 0xff, 0xff,
	0xff, 0x7f, 0x90, 0x19, 0xdc, 0x46, 0x3c, 0x10, 0x9b, 0xf4, 0x20, 0x0a, 0x21, 0xd2, 0x4a, 0xf5,
	0x5c, 0xa2, 0xc1, 0xa9, 0x39, 0x69, 0x2e, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x49, 0x99, 0x79, 0xe9,
	0xbe, 0x10, 0x13, 0x85, 0xa4, 0xb9, 0x38, 0x4b, 0x2a, 0x0b, 0x52, 0xe3, 0xf3, 0x12, 0x73, 0x21,
	0x8e, 0xe0, 0x0c, 0xe2, 0x00, 0x09, 0xf8, 0x25, 0xe6, 0xa6, 0x0a, 0x29, 0x72, 0xf1, 0x40, 0x6d,
	0x8e, 0x4f, 0x49, 0x2c, 0x49, 0x04, 0xbb, 0x86, 0x27, 0x88, 0x1b, 0x2a, 0xe6, 0x92, 0x58, 0x92,
	0x48, 0xac, 0x03, 0x92, 0xd8, 0xc0, 0x62, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x18,
	0xbb, 0x1e, 0x0c, 0x01, 0x00, 0x00,
}
