// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5b2751face2128a3, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5b2751face2128a3, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type RemoteShellRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Stdin                []byte   `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteShellRequest) Reset()         { *m = RemoteShellRequest{} }
func (m *RemoteShellRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteShellRequest) ProtoMessage()    {}
func (*RemoteShellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5b2751face2128a3, []int{2}
}
func (m *RemoteShellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteShellRequest.Unmarshal(m, b)
}
func (m *RemoteShellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteShellRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteShellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteShellRequest.Merge(dst, src)
}
func (m *RemoteShellRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteShellRequest.Size(m)
}
func (m *RemoteShellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteShellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteShellRequest proto.InternalMessageInfo

func (m *RemoteShellRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteShellRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RemoteShellRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

type RemoteShellResponse struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Stdout               []byte   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteShellResponse) Reset()         { *m = RemoteShellResponse{} }
func (m *RemoteShellResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteShellResponse) ProtoMessage()    {}
func (*RemoteShellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5b2751face2128a3, []int{3}
}
func (m *RemoteShellResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteShellResponse.Unmarshal(m, b)
}
func (m *RemoteShellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteShellResponse.Marshal(b, m, deterministic)
}
func (dst *RemoteShellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteShellResponse.Merge(dst, src)
}
func (m *RemoteShellResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteShellResponse.Size(m)
}
func (m *RemoteShellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteShellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteShellResponse proto.InternalMessageInfo

func (m *RemoteShellResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *RemoteShellResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *RemoteShellResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

type TextToSpeechRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextToSpeechRequest) Reset()         { *m = TextToSpeechRequest{} }
func (m *TextToSpeechRequest) String() string { return proto.CompactTextString(m) }
func (*TextToSpeechRequest) ProtoMessage()    {}
func (*TextToSpeechRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5b2751face2128a3, []int{4}
}
func (m *TextToSpeechRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextToSpeechRequest.Unmarshal(m, b)
}
func (m *TextToSpeechRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextToSpeechRequest.Marshal(b, m, deterministic)
}
func (dst *TextToSpeechRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextToSpeechRequest.Merge(dst, src)
}
func (m *TextToSpeechRequest) XXX_Size() int {
	return xxx_messageInfo_TextToSpeechRequest.Size(m)
}
func (m *TextToSpeechRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TextToSpeechRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TextToSpeechRequest proto.InternalMessageInfo

func (m *TextToSpeechRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TextToSpeechResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextToSpeechResponse) Reset()         { *m = TextToSpeechResponse{} }
func (m *TextToSpeechResponse) String() string { return proto.CompactTextString(m) }
func (*TextToSpeechResponse) ProtoMessage()    {}
func (*TextToSpeechResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5b2751face2128a3, []int{5}
}
func (m *TextToSpeechResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextToSpeechResponse.Unmarshal(m, b)
}
func (m *TextToSpeechResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextToSpeechResponse.Marshal(b, m, deterministic)
}
func (dst *TextToSpeechResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextToSpeechResponse.Merge(dst, src)
}
func (m *TextToSpeechResponse) XXX_Size() int {
	return xxx_messageInfo_TextToSpeechResponse.Size(m)
}
func (m *TextToSpeechResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TextToSpeechResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TextToSpeechResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request)(nil), "main.Request")
	proto.RegisterType((*Response)(nil), "main.Response")
	proto.RegisterType((*RemoteShellRequest)(nil), "main.RemoteShellRequest")
	proto.RegisterType((*RemoteShellResponse)(nil), "main.RemoteShellResponse")
	proto.RegisterType((*TextToSpeechRequest)(nil), "main.TextToSpeechRequest")
	proto.RegisterType((*TextToSpeechResponse)(nil), "main.TextToSpeechResponse")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_5b2751face2128a3) }

var fileDescriptor_server_5b2751face2128a3 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x6e, 0xc2, 0x30,
	0x14, 0x84, 0x15, 0xfe, 0x79, 0x62, 0x65, 0x10, 0xb2, 0xba, 0x8a, 0xbc, 0x62, 0xd5, 0x2e, 0x7a,
	0x84, 0xde, 0xc0, 0x70, 0x01, 0xb7, 0x19, 0x41, 0x24, 0x6c, 0xa7, 0x7e, 0x8f, 0x8a, 0xe3, 0x57,
	0x89, 0x1d, 0xa4, 0xec, 0xe6, 0x1b, 0xd9, 0x33, 0xa3, 0x47, 0x3b, 0x46, 0xfa, 0x43, 0x7a, 0xef,
	0x52, 0x94, 0xa8, 0x16, 0xde, 0xb5, 0xc1, 0x6c, 0x69, 0x6d, 0xf1, 0xfb, 0x00, 0x8b, 0x21, 0xda,
	0x58, 0x70, 0x17, 0x03, 0xc3, 0x58, 0x52, 0x16, 0x3e, 0x0a, 0xce, 0x37, 0xdc, 0xef, 0xe5, 0x85,
	0x52, 0xb4, 0x08, 0xce, 0x43, 0x57, 0x75, 0x75, 0xda, 0xda, 0x41, 0xf7, 0x9e, 0x4b, 0x57, 0xd6,
	0xb3, 0x7a, 0xde, 0x7b, 0xbd, 0x56, 0x07, 0x5a, 0xb2, 0x34, 0x6d, 0xd0, 0xf3, 0xba, 0x3a, 0xed,
	0x6c, 0x06, 0xe3, 0x68, 0x3f, 0xc9, 0xcc, 0x55, 0xea, 0x8d, 0x36, 0x78, 0xb6, 0xf2, 0x15, 0x9b,
	0x1c, 0xbc, 0xb4, 0x2f, 0x56, 0x47, 0x5a, 0xb1, 0x34, 0xf1, 0x21, 0x7a, 0x36, 0x24, 0x15, 0x2a,
	0x3e, 0x52, 0x2a, 0x0d, 0x85, 0xcc, 0x07, 0xed, 0x2f, 0x78, 0xca, 0x25, 0x9e, 0x3b, 0xe0, 0xe7,
	0x36, 0xee, 0xd6, 0xb4, 0xf6, 0x60, 0x76, 0xd7, 0x71, 0xfa, 0x88, 0xe6, 0x48, 0x87, 0xe9, 0x87,
	0x3c, 0xea, 0x7b, 0x35, 0xdc, 0xe8, 0xf3, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x41, 0x3b, 0x6d,
	0x33, 0x01, 0x00, 0x00,
}
