// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteShellRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Stdin                []byte   `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteShellRequest) Reset()         { *m = RemoteShellRequest{} }
func (m *RemoteShellRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteShellRequest) ProtoMessage()    {}
func (*RemoteShellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_12ceca2893897132, []int{0}
}
func (m *RemoteShellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteShellRequest.Unmarshal(m, b)
}
func (m *RemoteShellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteShellRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteShellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteShellRequest.Merge(dst, src)
}
func (m *RemoteShellRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteShellRequest.Size(m)
}
func (m *RemoteShellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteShellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteShellRequest proto.InternalMessageInfo

func (m *RemoteShellRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteShellRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RemoteShellRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

type RemoteShellResponse struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Stdout               []byte   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteShellResponse) Reset()         { *m = RemoteShellResponse{} }
func (m *RemoteShellResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteShellResponse) ProtoMessage()    {}
func (*RemoteShellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_12ceca2893897132, []int{1}
}
func (m *RemoteShellResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteShellResponse.Unmarshal(m, b)
}
func (m *RemoteShellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteShellResponse.Marshal(b, m, deterministic)
}
func (dst *RemoteShellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteShellResponse.Merge(dst, src)
}
func (m *RemoteShellResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteShellResponse.Size(m)
}
func (m *RemoteShellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteShellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteShellResponse proto.InternalMessageInfo

func (m *RemoteShellResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *RemoteShellResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *RemoteShellResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

type TextToSpeechRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextToSpeechRequest) Reset()         { *m = TextToSpeechRequest{} }
func (m *TextToSpeechRequest) String() string { return proto.CompactTextString(m) }
func (*TextToSpeechRequest) ProtoMessage()    {}
func (*TextToSpeechRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_12ceca2893897132, []int{2}
}
func (m *TextToSpeechRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextToSpeechRequest.Unmarshal(m, b)
}
func (m *TextToSpeechRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextToSpeechRequest.Marshal(b, m, deterministic)
}
func (dst *TextToSpeechRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextToSpeechRequest.Merge(dst, src)
}
func (m *TextToSpeechRequest) XXX_Size() int {
	return xxx_messageInfo_TextToSpeechRequest.Size(m)
}
func (m *TextToSpeechRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TextToSpeechRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TextToSpeechRequest proto.InternalMessageInfo

func (m *TextToSpeechRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TextToSpeechResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextToSpeechResponse) Reset()         { *m = TextToSpeechResponse{} }
func (m *TextToSpeechResponse) String() string { return proto.CompactTextString(m) }
func (*TextToSpeechResponse) ProtoMessage()    {}
func (*TextToSpeechResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_12ceca2893897132, []int{3}
}
func (m *TextToSpeechResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextToSpeechResponse.Unmarshal(m, b)
}
func (m *TextToSpeechResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextToSpeechResponse.Marshal(b, m, deterministic)
}
func (dst *TextToSpeechResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextToSpeechResponse.Merge(dst, src)
}
func (m *TextToSpeechResponse) XXX_Size() int {
	return xxx_messageInfo_TextToSpeechResponse.Size(m)
}
func (m *TextToSpeechResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TextToSpeechResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TextToSpeechResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RemoteShellRequest)(nil), "main.RemoteShellRequest")
	proto.RegisterType((*RemoteShellResponse)(nil), "main.RemoteShellResponse")
	proto.RegisterType((*TextToSpeechRequest)(nil), "main.TextToSpeechRequest")
	proto.RegisterType((*TextToSpeechResponse)(nil), "main.TextToSpeechResponse")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_12ceca2893897132) }

var fileDescriptor_server_12ceca2893897132 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x6a, 0x87, 0x30,
	0x10, 0x85, 0xf1, 0xf7, 0xaf, 0xed, 0xe0, 0x2a, 0x8a, 0x84, 0xae, 0x24, 0x2b, 0x57, 0xed, 0xa2,
	0x47, 0xe8, 0x0d, 0xa2, 0x17, 0x48, 0xeb, 0xa0, 0x82, 0x49, 0x6c, 0x66, 0x2c, 0x1e, 0xbf, 0xa8,
	0xb1, 0xe0, 0xee, 0x7d, 0x0f, 0xf2, 0xf2, 0x31, 0x90, 0x12, 0x86, 0x5f, 0x0c, 0x6f, 0x53, 0xf0,
	0xec, 0xc5, 0xcd, 0x9a, 0xc1, 0x29, 0x0d, 0x42, 0xa3, 0xf5, 0x8c, 0x75, 0x8f, 0xe3, 0xa8, 0xf1,
	0x67, 0x46, 0x62, 0x21, 0xe0, 0xe6, 0x8c, 0x45, 0x99, 0x94, 0x49, 0xf5, 0xa2, 0xb7, 0xbc, 0x76,
	0x26, 0x74, 0x24, 0x2f, 0xe5, 0x75, 0xed, 0xd6, 0x2c, 0x72, 0xb8, 0x13, 0xb7, 0x83, 0x93, 0xd7,
	0x32, 0xa9, 0x52, 0xbd, 0x83, 0x32, 0x90, 0x9d, 0x36, 0x69, 0xf2, 0x8e, 0x50, 0xbc, 0xc2, 0x33,
	0x2e, 0x03, 0x7f, 0xfa, 0x76, 0x1f, 0xbe, 0xeb, 0x7f, 0x16, 0x05, 0x3c, 0x88, 0x5b, 0x3f, 0xb3,
	0xbc, 0x6c, 0x4b, 0x91, 0x62, 0x8f, 0x21, 0xc4, 0x1f, 0x22, 0xa9, 0x77, 0xc8, 0x1a, 0x5c, 0xb8,
	0xf1, 0xf5, 0x84, 0xf8, 0xdd, 0x1f, 0xde, 0x12, 0x9e, 0x2c, 0x12, 0x99, 0xee, 0x50, 0x3f, 0x50,
	0x15, 0x90, 0x9f, 0x1f, 0xec, 0x52, 0x5f, 0x8f, 0xed, 0x18, 0x1f, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x71, 0x16, 0xf2, 0x1c, 0x01, 0x00, 0x00,
}
